export const DEPOSIT = "DEPOSIT";
export const WITHDRAW = "WITHDRAW";
export const BUYBITCOIN = "BUYBITCOIN";
export const SELLBITCOIN = "SELLBITCOIN";
export const INCREASEBITCOINPRICE = "INCREASEBITCOINPRICE";
export const DECREASEBITCOINPRICE = "DECREASEBITCOINPRICE";
export const ADDHISTORY = "ADDHISTORY";
